package com.recruitment.backend.notifications.domain.enums;

public enum NotificationType {
    OTP,
    APPLICATION_SUBMITTED,
    APPLICATION_RESULT,
    JOB_MATCH,
    USER_REGISTERED,
    COMPANY_VERIFIED,
    COMPANY_REJECTED,
    COMPANY_MORE_INFO_REQUESTED,
    JOB_APPROVED,
    JOB_REJECTED,
    JOB_FLAGGED,
    JOB_CLOSED,
    ADMIN_COMPANY_REVIEW_REQUESTED,
    ADMIN_JOB_REVIEW_REQUESTED
}
